### Get all groups
GET https://localhost:5001/api/group

### Create a group
POST https://localhost:5001/api/group
Content-Type: application/json

{
    "name": "Babyfoot"
}

### Try to create an existing group
POST https://localhost:5001/api/group
Content-Type: application/json

{
    "name": "Football"
}

### Delete a group
DELETE https://localhost:5001/api/group/-1

### Delete a non existing group
DELETE https://localhost:5001/api/group/10

### Join an existing group
PUT https://localhost:5001/api/group/0
Content-Type: application/json

{
    "id": 123
}
### Join a not existing group
PUT https://localhost:5001/api/group/10
Content-Type: application/json

{
    "id": 123
}